dev-deployment:
 variables:
   GIT_STRATEGY: fetch
 script:
   - bash ~/gitlab/node22/node22-projectdeploy-pnpm-docker-v1.sh
 environment:
     name: Development
     url : https://consultly-api.dedicateddevelopers.us
 tags:
         - node-docker4
 only:
   - dev
